spring:
  config:
    activate:
      on-profile: local
    import:
      #      - optional:file:.env[.properties] #TODO: .env 경로를 실행 위치에서 찾음. 경로 미확정
      - optional:classpath:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  cloud:
    vault:
      enabled: false

logging:
  level:
    com.efa73.trackee: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.core.env: DEBUG #TODO: 환경 변수 로드 과정 디버깅 - 나중에 제거

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: "env"
