server:
  port: 8080

spring:
  application:
    name: charlee

  profiles:
    active: local

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?useSSL=${MYSQL_SSL}&useUnicode=${MYSQL_UNICODE}&allowPublicKeyRetrieval=${MYSQL_KEY}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secretKey: ${JWT_SECRET}
  access:
    expiration: ${JWT_EXP_TIME}
    header: ${JWT_ACCESS_HEADER}
  refresh:
    expiration: ${JWT_EXP_TIME}
    header: ${JWT_REFRESH_HEADER}


admin:
  name: ${ADMIN_NAME}
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

collector:
  url: http://localhost:8081/collector
